### PR TITLE
Adding SSO CAS to Wekan

### PR DESCRIPTION
**Pull request by ppoulard**
This is the integration to Wekan of the package atoy40:meteor-account-cas.
See https://github.com/wekan/wekan/issues/620
There is also a change in wekan build project : https://github.com/wekan/wekan/pull/1742

Usage: 
-without settings, CAS is disabled
-the presence of the settings indicated here https://atmospherejs.com/atoy40/accounts-cas will activate CAS ; don't forget to specify the ROOT_URL properly

### CODE REVIEW

**Comment by andresmanelli** [comment]
@ppoulard why the package is added in the Dockerfile ? (I don't see that line in the main repo. Thanks !

**Comment by ppoulard** [comment]
Hi, 
maybe because it was working with it ?

**Comment by xet7** [comment]
https://github.com/wekan/wekan/blob/devel/Dockerfile#L261

https://github.com/wekan/wekan/blob/devel/.meteor/packages#L90

https://github.com/wekan/meteor-accounts-cas

**Comment by andresmanelli** [comment]
Thanks, I'll update the PR later !

**Comment by andresmanelli** [comment]
@ppoulard Some changes were already in the updated Dockerfile, so I updated your branch.

**Pull request merged**
